# Generated by Django 3.2.5 on 2021-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text_blog',
            field=models.CharField(max_length=5000),
        ),
    ]
