# Generated by Django 4.1.7 on 2023-02-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211218_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='discription',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
